linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - gosec
    - unconvert
    - revive
    - gocognit
    - gocyclo
  fast: true

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/Nerzal/gocloak
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true

issues:
  exclude-dirs:
    - (^|/)testdata($|/)
  exclude-dirs-use-default: false
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - gocognit
  exclude:
    - should have a package comment
