version: '3'

services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_IMPORT: /tmp/gocloak-realm.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      JAVA_OPTS_APPEND: "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8080:8080"
    volumes:
      -  ./testdata/gocloak-realm.json:/tmp/gocloak-realm.json