version: '3'

services:
  keycloak:
    build: .
    command: -Dauto-build -Dfeatures=preview
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - "8080:8080"
    volumes:
      -  ./testdata/gocloak-realm.json:/opt/keycloak/data/import/gocloak-realm.json
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev --features=preview --import-realm"]
 