name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.26'

      - name: Run Keycloak
        run: |
          make start-keycloak
          sleep 15

      - name: Unit Tests
        run: |
          go test -failfast -race -cover -coverprofile=coverage.txt -covermode=atomic -p 100 -cpu 1,2 -bench . -benchmem > test.log
          cat test.log

      - name: Failed Logs
        if: failure()
        run: |
          cat test.log
          docker ps
          docker logs keycloak

      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }} 

      - name: Store Benchmark Result
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "go"
          output-file-path: test.log
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      - name: GoReportCard
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/Nerzal/gocloak"